version: "3.9"

services:
  webap:
    image: darchlabs/onboarding-app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "5800:5800"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/redis

